### ISSUE TITLE
Switch build systems: mkconfig -> CMake

### ISSUE THREAD

**Issue by ctrlaltf2** [computernewb/collab-vm-server-1.2#57]
Quoting modeco:

> one of my first goals for 1.3 is to remove mkconfig
...
> love it or hate it mkconfig is a piece of garbage

agreed

**Comment by modeco80** [comment]
Yeeeah honestly mkconfig sucks, but it's like "it sucks less"

the old Autotools buildsystem (which makes no sense - cosmic didn't even include aclocal, so there's no point in requiring Autotools - just use a plain makefile?) was probably the worst

Now that OSSP-uuid and ODB are gone, this is probably basically just short work (I had planned to do this a couple years ago, I no longer have the data, and I gave up trying to get ossp uuid to work or something, as I was entirely remaking the buildsystem for ODB/osspuuid because they both also used icky autotools)

**Comment by modeco80** [comment]
I'm also not trying to nitpick (at least not in a mean way, please don't take it like that) but websocketmm and such i would consider separate modules, so they should probably be built as seperate static libraries (guacamole is a bit harder, since cosmic performed "surgery" on it and then rewrote bits of it, however, I'd consider it also a separate module)

**Comment by ctrlaltf2** [comment]
I totally agree, this is on my todo list. I need to do a bit of (re)learning on nesting CMake projects like this but I will be doing it this way.

**Comment by ctrlaltf2** [comment]
Merged, that's a wrap folks

**Comment by ctrlaltf2** [comment]
Todo for doc: edit readme for using `cmake -D CMAKE_C_COMPILER=/usr/bin/clang -D CMAKE_CXX_COMPILER=/usr/bin/clang++` and other cmake commands for building (including ccmake and stuff).
