### ISSUE TITLE
Look into replacing sqlite_orm

### ISSUE THREAD

**Issue by ctrlaltf2** [computernewb/collab-vm-server-1.2#62]
This is due to the issue that the library has when building with GCC (see issue 583 at https://github.com/fnc12/sqlite_orm). On their issue tracker, it's marked as wontfix/notabug.

Some promising alternatives to look into:
* https://github.com/SqliteModernCpp/sqlite_modern_cpp
* https://github.com/paulftw/hiberlite

**Comment by ctrlaltf2** [comment]
If you're here from sqlite_orm repo I _did not_ mean for this issue to get linked from your issue tracker. Sorry about that!

**Comment by modeco80** [comment]
Meh, I'd say just add a compiler ID check for gnu and add template depth flags if it's actually gcc and not clang. Ideally, GCC devs should get their shit together and fix the ICE, since it's on them, but yknow.

Either that or say screw it and use sqlite on our own over a minimal wrapper suited for us... kinda grody, but it would work

**Comment by modeco80** [comment]
Gonna be a bit brutally honest here - I think we should just do what I proposed and add flags to mitigate the GCC ICE, as the issue is on them (and it may not even be fixed yet, knowing gcc devs), and will happen with pretty much any abuse of templates. (apparently template depth isn't actually needed, but a couple optimizations need to be disabled. Could probably disable them solely for the database). 

I don't really think there's a point in switching to another library and I think for now sqlite_orm is good enough for our usage of sqlite3 (and any further usage, at least, depending on scalability.)  

Provided we need to switch to another database engine entirely (as sqlite3 and scalable are things which usually don't go together), I think then talks about a library would be better at that time.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
why not just use plain txt or xml or json for database?

is not actually a database it doesn’t store that much things mostly config and vms which…

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
database just makes it harder to work with and editing for both dev and users.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
most spigot plugins use xml or json, they are easy to edit, and very useful.

**Comment by dakrk** [comment]
HAHAHAHAHAAHHA No

**Comment by modeco80** [comment]
yeah store a bunch of users and password hashes in json That will go very well

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
> store a bunch of users and password hashes in json That will go very well

STORING USERNAME AND PASSWORD HASHES? WHEN WHERE WHY HOW?
maybe make …


but it’s readable and not encrypted anyway? colllabvm.db is just a text file like json or xml.

**Comment by dakrk** [comment]
> colllabvm.db is just a text file like json or xml

lol no it really isn't
most of the contents of the file are text yes but it's still a binary file format

> WHEN WHERE WHY HOW?

the admin and moderator passwords are eventually going to be hashed in the database
for usernames, you'll see eventually

**Comment by modeco80** [comment]
Closing. A possible full code rewrite may involve a decision like this being reconsidered.
(I'm considering PostgreSQL if I do make a switch because we *would* be storing lots more data, e.g. accounts and the like.)
