### ISSUE TITLE
Use a static function to encode outgoing WS messages

### ISSUE THREAD

**Issue by ctrlaltf2** [computernewb/collab-vm-server-1.2#64]
e.g. https://github.com/ctrlaltf2/lets-play/blob/master/src/LetsPlayProtocol.cpp encode function except variadic.
Should slim the codebase down a bit

**Comment by modeco80** [comment]
ah.. This is nice and sorta like the `PushAction<TAction>()` thing I did, yeah. That however *needs* access to CollabVMServer members so it's not static.

One thing which would be great is if each thing to be encoded used an adl overload of like 
```cpp
// Encodes a single element of type T into the output string specified.
void encode_element(std::string& output, T t);
```
so that the user facing encode function basically just becomes a fold of encode_element() calls over all the things you specified. 

This would both be great for avoiding template bloat, but it'd also allow us to directly serialize say the UserList or something instead of doing the weird stuff the server does when deciding to serialize these things. And, since the main template function simply performs ADL lookup for if encode_element(output, T{}) is a thing, this can be extended as much as we possibly can fathom.

But back on the topic, this would DEFINITELY clean up the code, and probably shave quite a bit off the LOC of the main CollabVMServer class implementation. Would kinda move the LOC into the implementation of encode_element for all the types we want (I think for enums, you can drop something in constraining to `is_enum_v<T>`, so that's not a problem), but I consider more LOC a good thing if it greatly improves the maintainability of the server.

**Comment by modeco80** [comment]
The general consensus seems to be that Guacamole is going to just be ripped out, as updating it would not be worthwhile..

Closing for now, although this can be re-opened if some wacko actually decides to try and wrangle Cosmic-Guac.
